# Generated by Django 4.2.19 on 2025-04-03 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabloide', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='slug_city',
            field=models.SlugField(blank=True, default=''),
        ),
    ]
