# Generated by Django 4.2.19 on 2025-04-07 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tabloide', '0002_alter_store_slug_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='slug_city',
            new_name='city_slug',
        ),
    ]
