# Generated by Django 4.2.19 on 2025-04-07 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabloide', '0003_rename_slug_city_store_city_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='order_promo',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ordem'),
        ),
    ]
