# Generated by Django 4.2.19 on 2025-04-09 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tabloide', '0004_promotion_order_promo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Código',
            new_name='codigo',
        ),
    ]
